name: 'CI'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    - run: make test

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    - uses: azure/setup-kubectl@v1
    - uses: azure/setup-helm@v1
      with:
        version: v3.8.0
    - uses: engineerd/setup-kind@v0.5.0
    - run: make integration-test
    - if: failure()
      run: |
        kubectl config set-context kind-kind --namespace helm-cleanup-1
        helm list --all-namespaces
