name: 'CI'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.2
    - run: make test

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: azure/setup-kubectl@v1
    - uses: azure/setup-helm@v1
      with:
        version: v3.8.0
    - uses: engineerd/setup-kind@v0.5.0
    - run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
    - run: make integration-test
    - if: failure()
      run: |
        kubectl config set-context kind-kind --namespace test-namespace
        helm list --all
        echo "==========================="
        kubectl get pods --no-headers | awk '{print $1}' | xargs -L 1 kubectl logs
